# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # State1.
  class State1Enum
    STATE1_ENUM = [
      # TODO: Write general description for NOT_RECORDING
      NOT_RECORDING = 'NOT_RECORDING'.freeze,

      # TODO: Write general description for PAUSED
      PAUSED = 'PAUSED'.freeze,

      # TODO: Write general description for RECORDING
      RECORDING = 'RECORDING'.freeze
    ].freeze
  end
end
