# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # State.
  class StateEnum
    STATE_ENUM = [
      # TODO: Write general description for DISCONNECTED
      DISCONNECTED = 'DISCONNECTED'.freeze,

      # TODO: Write general description for ANSWERED
      ANSWERED = 'ANSWERED'.freeze,

      # TODO: Write general description for INITIATED
      INITIATED = 'INITIATED'.freeze
    ].freeze
  end
end
