# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Transcript Model.
  class Transcript < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :text

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :confidence

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['text'] = 'text'
      @_hash['confidence'] = 'confidence'
      @_hash
    end

    def initialize(text = nil,
                   confidence = nil)
      @text = text
      @confidence = confidence
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      text = hash['text']
      confidence = hash['confidence']

      # Create object from extracted values.
      Transcript.new(text,
                     confidence)
    end
  end
end
