gemAuthor: Bandwidth
gemAuthorEmail: dx@bandwidth.com
gemDescription: The official client SDK for Bandwidth's Voice, Messaging, MFA, and WebRTC APIs
gemHomepage: https://github.com/Bandwidth/ruby-sdk
gemLicense: MIT
gemName: bandwidth-sdk
gemRequiredRubyVersion: '>=2.7'
gemSummary: Bandwidth Ruby SDK
gemVersion: 11.0.0
library: faraday
moduleName: Bandwidth
templateDir: custom_templates
files:
  gemspec.mustache:
    destinationFilename: bandwidth-sdk.gemspec
  gem.mustache:
    folder: lib
    destinationFilename: bandwidth-sdk.rb
  README.mustache:
    destinationFilename: README.md
