=begin
#Bandwidth

#Bandwidth's Communication APIs

The version of the OpenAPI document: 1.0.0
Contact: letstalk@bandwidth.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Bandwidth::LookupRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Bandwidth::LookupRequest do
  let(:instance) { Bandwidth::LookupRequest.new }

  describe 'test an instance of LookupRequest' do
    it 'should create an instance of LookupRequest' do
      expect(instance).to be_instance_of(Bandwidth::LookupRequest)
    end
  end
  describe 'test attribute "tns"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
