=begin
#Bandwidth

#Bandwidth's Communication APIs

The version of the OpenAPI document: 1.0.0
Contact: letstalk@bandwidth.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end


require 'json'
require 'date'

# Unit tests for Bandwidth::MachineDetectionModeEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Bandwidth::MachineDetectionModeEnum do
  let(:instance) { Bandwidth::MachineDetectionModeEnum.new }

  describe 'test an instance of MachineDetectionModeEnum' do
    it 'should create an instance of MachineDetectionModeEnum' do
      expect(instance).to be_instance_of(Bandwidth::MachineDetectionModeEnum)
    end
  end
end
