=begin
#Bandwidth

#Bandwidth's Communication APIs

The version of the OpenAPI document: 1.0.0
Contact: letstalk@bandwidth.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Bandwidth::UpdateCallRecording
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Bandwidth::UpdateCallRecording do
  let(:instance) { Bandwidth::UpdateCallRecording.new }

  describe 'test an instance of UpdateCallRecording' do
    it 'should create an instance of UpdateCallRecording' do
      expect(instance).to be_instance_of(Bandwidth::UpdateCallRecording)
    end
  end
  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
