=begin
#Bandwidth

#Bandwidth's Communication APIs

The version of the OpenAPI document: 1.0.0
Contact: letstalk@bandwidth.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Bandwidth
  class MessageStatusEnum
    RECEIVED = "RECEIVED".freeze
    QUEUED = "QUEUED".freeze
    SENDING = "SENDING".freeze
    SENT = "SENT".freeze
    FAILED = "FAILED".freeze
    DELIVERED = "DELIVERED".freeze
    ACCEPTED = "ACCEPTED".freeze
    UNDELIVERED = "UNDELIVERED".freeze

    def self.all_vars
      @all_vars ||= [RECEIVED, QUEUED, SENDING, SENT, FAILED, DELIVERED, ACCEPTED, UNDELIVERED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if MessageStatusEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #MessageStatusEnum"
    end
  end
end
