=begin
#Bandwidth
#Bandwidth's Communication APIs
The version of the OpenAPI document: 1.0.0
Contact: letstalk@bandwidth.com
Generated by: https://openapi-generator.tech
Generator version: 7.17.0
=end

require 'date'
require 'time'

module Bandwidth
    #BXML <Refer> verb model. Sends a SIP REFER for an inbound SIP URI call
  class Refer < ApiModelBase
    attr_accessor :refer_complete_url
    attr_accessor :refer_complete_method
    attr_accessor :tag
    attr_accessor :sip_uri

    def self.attribute_map
      {
        :'refer_complete_url' => :'referCompleteUrl',
        :'refer_complete_method' => :'referCompleteMethod',
        :'tag' => :'tag',
        :'sip_uri' => :'sipUri'
      }
    end

    def self.acceptable_attribute_map
      attribute_map
    end

    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    def self.openapi_types
      {
        :'refer_complete_url' => :'String',
        :'refer_complete_method' => :'ReferCompleteMethodEnum',
        :'tag' => :'String',
        :'sip_uri' => :'SipUri'
      }
    end

    def self.openapi_nullable
      Set.new([:'refer_complete_url', :'refer_complete_method', :'tag'])
    end

    def initialize(attributes = {})
      raise ArgumentError, "attributes must be a Hash" unless attributes.is_a?(Hash)

      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) do |(k, v), h|
        raise ArgumentError, "`#{k}` is not a valid attribute in `Bandwidth::Refer`." unless acceptable_attribute_map.key?(k.to_sym)
        h[k.to_sym] = v
      end

      self.refer_complete_url = attributes[:'refer_complete_url'] if attributes.key?(:'refer_complete_url')
      self.refer_complete_method = attributes[:'refer_complete_method'] if attributes.key?(:'refer_complete_method')
      self.tag = attributes[:'tag'] if attributes.key?(:'tag')
      self.sip_uri = attributes[:'sip_uri'] if attributes.key?(:'sip_uri')

      # required nested destination
      raise ArgumentError, "`sip_uri` is required for Bandwidth::Refer" if self.sip_uri.nil?
      # optional validation
      if !self.refer_complete_method.nil?
        ReferCompleteMethodEnum.build_from_hash(self.refer_complete_method)
      end
      if !self.tag.nil? && self.tag.length > 256
        raise ArgumentError, "`tag` max length is 256"
      end
    end

    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && !attributes[attribute_map[key]].nil?
          transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next unless is_nullable && instance_variable_defined?(:"@#{attr}")
        end
        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end