# bandwidth
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Bandwidth
  # Media Model.
  class Media < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :content

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :content_length

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :media_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['content'] = 'content'
      @_hash['content_length'] = 'contentLength'
      @_hash['media_name'] = 'mediaName'
      @_hash
    end

    def initialize(content = nil,
                   content_length = nil,
                   media_name = nil)
      @content = content
      @content_length = content_length
      @media_name = media_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      content = hash['content']
      content_length = hash['contentLength']
      media_name = hash['mediaName']

      # Create object from extracted values.
      Media.new(content,
                content_length,
                media_name)
    end
  end
end
