name: Deploy SDK

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy to Rubygems
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Rubygems
      uses: ./.github/actions/deploy
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
