name: Deploy SDK

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy to Rubygems
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Rubygems
      uses: ./.github/actions/deploy
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
