name: Smoke Test

on:
  schedule:
    - cron: "0 4 * * *"
  pull_request:
    branches:
      - main
    paths:
      - "spec/smoke/*"
      - ".github/workflows/test-smoke.yml"
      - ".github/actions/smoke-test/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  BW_USERNAME: ${{ secrets.BW_USERNAME }}
  BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
  BW_USERNAME_FORBIDDEN: ${{ secrets.BW_USERNAME_FORBIDDEN }}
  BW_PASSWORD_FORBIDDEN: ${{ secrets.BW_PASSWORD_FORBIDDEN }}
  USER_NUMBER: ${{ secrets.USER_NUMBER }}
  BASE_CALLBACK_URL: ${{ secrets.BASE_CALLBACK_URL }}
  MANTECA_ACTIVE_NUMBER: ${{ secrets.MANTECA_ACTIVE_NUMBER }}
  MANTECA_IDLE_NUMBER: ${{ secrets.MANTECA_IDLE_NUMBER }}
  MANTECA_BASE_URL: ${{ secrets.MANTECA_BASE_URL }}
  MANTECA_APPLICATION_ID: ${{ secrets.MANTECA_APPLICATION_ID }}

jobs:
  test_main:
    name: Smoke Test
    runs-on: ubuntu-latest
    env:
      BW_NUMBER: ${{ secrets.BW_NUMBER }}
      BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
      BW_VOICE_APPLICATION_ID: ${{ secrets.BW_VOICE_APPLICATION_ID }}
      BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
    steps:
      - name: Smoke Test
        uses: ./.github/actions/smoke-test

  test_main_up:
    name: Smoke Test UP Account
    runs-on: ubuntu-latest
    env:
      BW_NUMBER: ${{ secrets.BW_UP_NUMBER }}
      BW_ACCOUNT_ID: ${{ secrets.BW_UP_ACCOUNT_ID }}
      BW_VOICE_APPLICATION_ID: ${{ secrets.BW_UP_VOICE_APPLICATION_ID }}
      BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_UP_MESSAGING_APPLICATION_ID }}
    steps:
      - name: Smoke Test
        uses: ./.github/actions/smoke-test

  notify_for_failures:
    name: Notify for Failures
    needs: [test_main]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack of Failures
        uses: Bandwidth/build-notify-slack-action@v2.0.0
        with:
          job-status: failure
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
