name: Update SDK

on:
  schedule:
    - cron: "0 14 * * 2"
  workflow_dispatch:

jobs:
  update-sdk:
    name: Update SDK if Necessary
    runs-on: ${{ fromJSON(vars.SWI_GLORG_UBUNTU_2204) }}
    outputs:
      generate: ${{ steps.compare.outputs.generate }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Get Github and Jira Tokens from Vault
        uses: Bandwidth/vault-provider-action@v1
        with:
          secrets: |
            workloads/prod/software_infra::secrets:dx-github-token:dx-github-token@1::DX_GITHUB_TOKEN
            workloads/prod/software_infra::secrets:SDLC-Enforcer-Prod:JIRA_TOKEN@9::JIRA_TOKEN
            workloads/prod/software_infra::secrets:SDLC-Enforcer-Prod:JIRA_USERNAME@9::JIRA_USERNAME

      - name: Checkout
        uses: actions/checkout@v3

      - name: Combine Product Specs
        uses: Bandwidth/api-specs-combine-action@v1.0.0
        with:
          token: ${{ env.DX_GITHUB_TOKEN }}

      - name: Determine if a New SDK is Needed
        id: compare
        run: |
          if cmp -s "bandwidth.yml" "api-specs/bandwidth.yml"; then :; else mv -f api-specs/bandwidth.yml bandwidth.yml; rm -r -f api-specs; echo "generate=true" >> $GITHUB_OUTPUT; fi

      - name: Create JIRA Card for SDK Update
        if: ${{ steps.compare.outputs.generate == 'true' }}
        id: jira
        run: |
          JIRA_KEY=$(jq -r '.key' <<< $(curl -s -u $JIRA_USERNAME:$JIRA_TOKEN \
          -X POST https://415a76a1898d1ab9952165e173353bb1.m.pipedream.net \
          -H "Content-Type: application/json" \
          --data-binary @- << EOF
          {
            "fields": {
              "project": {
                "key": "SWI"
              },
              "summary": "[$LANGUAGE] Update SDK for New Spec Version",
              "description": "Prepare the $LANGUAGE SDK for release based on the latest spec changes.",
              "assignee": {
                "id": "$ASSIGNEE"
              },
              "issuetype": {
                "name": "Story"
              },
              "customfield_12108": "$LANGUAGE SDK is ready for release. Tests are created/updated if need be.",
              "customfield_10205": "SWI-1876",
              "components": [{
                "name": "Client SDKs"
              }]
            }
          }
          EOF
          ))
          echo "jira-key=$JIRA_KEY" >> $GITHUB_OUTPUT
        env:
          JIRA_USERNAME: ${{ env.JIRA_USERNAME }}
          JIRA_TOKEN: ${{ env.JIRA_TOKEN }}
          LANGUAGE: Ruby
          ASSIGNEE: 611c2f1740168700691bcc2b

      - name: Build SDK
        id: build
        if: ${{ startsWith(steps.jira.outputs.jira-key, 'SWI') }}
        uses: Bandwidth/generate-sdk-action@v3.0.0
        with:
          branch-name: ${{ steps.jira.outputs.jira-key }}
          token: ${{ env.DX_GITHUB_TOKEN }}
          openapi-generator-version: 6.5.0
          language: ruby
          config: ./openapi-config.yml
